### PR TITLE
updates the publish.yml so it's not 🧓🏻

### PR DESCRIPTION
**Pull request by hiddenist**
I noticed a warning in the publish workflow saying that checkout v2 was using node 12!!

> * "The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-node@v2.4.1."
> * "The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files."
> * "The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files."

This updates `yarn` and the actions used in the workflow so that they're ~in the correct decade~ (okay fine, 14 was released in 2020) no longer using deprecated functionality and past-EOL node versions.

### CODE REVIEW

**Comment by hiddenist** [comment]
Unfortunately kinda hard to test this without publishing a new version. @mckelveygreg any ideas?

**Comment by mckelveygreg** [comment]
Yeah, imma give it a go with [act](https://nektosact.com/), and see if I can update things a bit

**Comment by hiddenist** [comment]
@mckelveygreg sweet, thanks for testing it! I'm good with this if you wan to toss an approval on

**Review by mckelveygreg — APPROVED** [review]
Whoops, approved

**Pull request merged**
